title: emoji.lgbt
email: cyber@emoji.lgbt
description: >-
  A collection of pride-themed emoji
domain: "emoji.lgbt"
baseurl: ""
url: "https://emoji.lgbt"
collections:
  emoji:
    output: true
  emoji_source:
    output: true
  emoji_json:
    output: true
defaults:
 - scope:
     path: "_emoji"
   values:
     layout: emoji-details
     permalink: /:collection/:title.html
 - scope:
     path: "_emoji_source"
   values:
     layout: emoji-source
     permalink: /assets/svg/:title.svg
 - scope:
     path: "_emoji_json"
   values:
     layout: emoji-json
     permalink: /api/v1/emoji/:title.json
sass:
  implementation: sass-embedded
  style: compressed
